development:
  adapter: postgresql
  encoding: unicode
  database: perfo_development
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  port: 5433

test:
  adapter: postgresql
  encoding: unicode
  database: perfo_development
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  port: 5433

production:
  adapter: postgresql
  encoding: unicode
  database: perfo_development
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  port: 5433

staging:
  adapter: postgresql
  encoding: unicode
  database: perfo_development
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  port: 5433


